---
galaxy_info:
  author: Chun Pan Yung
  description: System configuration, install frequent used packages.
  license: GPL-2.0-or-later

  min_ansible_version: "2.11"

  platforms:
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags: []
dependencies: []
