---
galaxy_info:
  author: Chun Pan Yung
  description: Install ansible development kits
  license: GPL-2.0-or-later

  min_ansible_version: "2.11"

  platforms:
    - name: Fedora
      versions:
        - all

  galaxy_tags: []

dependencies:
  - role: ansi_colle.linux.python
  - role: ansi_colle.linux.npm
